default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: latin_twit_development
  host: 'localhost'
  user: 'latin_twit'
  password: 'latintwit1'

test: &test
  <<: *default
  database: latin_twit_test

production:
  <<: *default
  <<: *development
